import os
import sqlite3
import math
from datetime import datetime, timezone, timedelta
from dotenv import load_dotenv

# Load env variables from backend/.env or current dir
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), ".env"))

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

USE_SUPABASE = bool(SUPABASE_URL and SUPABASE_KEY)
supabase_client = None

if USE_SUPABASE:
    try:
        from supabase import create_client
        supabase_client = create_client(SUPABASE_URL, SUPABASE_KEY)
        print("Connected to Supabase successfully!")
    except Exception as e:
        print(f"Failed to connect to Supabase: {e}. Falling back to SQLite.")
        USE_SUPABASE = False

DB_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "marunnundo.db"))

def get_sqlite_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    if USE_SUPABASE:
        print("Using Supabase. Ensure you have the following tables created:")
        print("""
        CREATE TABLE IF NOT EXISTS pharmacies (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            latitude DOUBLE PRECISION NOT NULL,
            longitude DOUBLE PRECISION NOT NULL,
            address TEXT,
            phone TEXT,
            source TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
        );
        CREATE TABLE IF NOT EXISTS scans (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            latitude DOUBLE PRECISION NOT NULL,
            longitude DOUBLE PRECISION NOT NULL,
            scanned_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
        );
        """)
        return
    
    # Initialize SQLite
    conn = get_sqlite_connection()
    cursor = conn.cursor()
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS pharmacies (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        latitude REAL NOT NULL,
        longitude REAL NOT NULL,
        address TEXT,
        phone TEXT,
        source TEXT,
        created_at TEXT DEFAULT (datetime('now', 'utc'))
    )
    """)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS scans (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        latitude REAL NOT NULL,
        longitude REAL NOT NULL,
        scanned_at TEXT DEFAULT (datetime('now', 'utc'))
    )
    """)
    conn.commit()
    conn.close()
    print(f"SQLite DB initialized at {DB_PATH}")

def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371.0  # Earth radius in kilometers
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat / 2) ** 2 +
         math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2) ** 2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c

def get_bounding_box(lat, lon, radius_km):
    # 1 degree lat = 111 km
    delta_lat = radius_km / 111.0
    # 1 degree lon = 111 * cos(lat) km
    cos_lat = math.cos(math.radians(lat))
    if cos_lat > 0:
        delta_lon = radius_km / (111.0 * cos_lat)
    else:
        delta_lon = 360.0
    return {
        "min_lat": lat - delta_lat,
        "max_lat": lat + delta_lat,
        "min_lon": lon - delta_lon,
        "max_lon": lon + delta_lon
    }

def has_scanned_nearby(lat: float, lon: float, radius_km: float, max_age_hours: int = 24) -> bool:
    bbox = get_bounding_box(lat, lon, radius_km)
    time_limit = (datetime.now(timezone.utc) - timedelta(hours=max_age_hours)).isoformat()
    
    if USE_SUPABASE:
        try:
            res = supabase_client.table("scans") \
                .select("latitude, longitude, scanned_at") \
                .gte("scanned_at", time_limit) \
                .gte("latitude", bbox["min_lat"]) \
                .lte("latitude", bbox["max_lat"]) \
                .gte("longitude", bbox["min_lon"]) \
                .lte("longitude", bbox["max_lon"]) \
                .execute()
            
            scans = res.data or []
            for scan in scans:
                dist = haversine_distance(lat, lon, scan["latitude"], scan["longitude"])
                if dist <= radius_km:
                    return True
        except Exception as e:
            print(f"Supabase scan check failed: {e}. Falling back to SQLite.")
            
    # SQLite
    try:
        conn = get_sqlite_connection()
        cursor = conn.cursor()
        cursor.execute("""
            SELECT latitude, longitude, scanned_at 
            FROM scans 
            WHERE latitude BETWEEN ? AND ? 
              AND longitude BETWEEN ? AND ?
              AND datetime(scanned_at) >= datetime('now', 'utc', ?)
        """, (bbox["min_lat"], bbox["max_lat"], bbox["min_lon"], bbox["max_lon"], f"-{max_age_hours} hours"))
        
        rows = cursor.fetchall()
        conn.close()
        
        for row in rows:
            dist = haversine_distance(lat, lon, row["latitude"], row["longitude"])
            if dist <= radius_km:
                return True
    except Exception as e:
        print(f"SQLite scan check failed: {e}")
        
    return False

def save_scan(lat: float, lon: float):
    if USE_SUPABASE:
        try:
            supabase_client.table("scans").insert({
                "latitude": lat,
                "longitude": lon,
                "scanned_at": datetime.now(timezone.utc).isoformat()
            }).execute()
            return
        except Exception as e:
            print(f"Failed to save scan to Supabase: {e}")
            
    try:
        conn = get_sqlite_connection()
        cursor = conn.cursor()
        cursor.execute("INSERT INTO scans (latitude, longitude) VALUES (?, ?)", (lat, lon))
        conn.commit()
        conn.close()
    except Exception as e:
        print(f"Failed to save scan to SQLite: {e}")

def get_pharmacies_in_radius(lat: float, lon: float, radius_km: float) -> list:
    bbox = get_bounding_box(lat, lon, radius_km)
    results = []
    
    if USE_SUPABASE:
        try:
            res = supabase_client.table("pharmacies") \
                .select("id, name, latitude, longitude, address, phone, source, created_at") \
                .gte("latitude", bbox["min_lat"]) \
                .lte("latitude", bbox["max_lat"]) \
                .gte("longitude", bbox["min_lon"]) \
                .lte("longitude", bbox["max_lon"]) \
                .execute()
            
            for item in (res.data or []):
                dist = haversine_distance(lat, lon, item["latitude"], item["longitude"])
                if dist <= radius_km:
                    item["distance"] = round(dist, 2)
                    results.append(item)
            return sorted(results, key=lambda x: x["distance"])
        except Exception as e:
            print(f"Supabase fetch failed: {e}. Falling back to SQLite.")
            
    # SQLite
    try:
        conn = get_sqlite_connection()
        cursor = conn.cursor()
        cursor.execute("""
            SELECT id, name, latitude, longitude, address, phone, source, created_at 
            FROM pharmacies 
            WHERE latitude BETWEEN ? AND ? 
              AND longitude BETWEEN ? AND ?
        """, (bbox["min_lat"], bbox["max_lat"], bbox["min_lon"], bbox["max_lon"]))
        
        rows = cursor.fetchall()
        conn.close()
        
        for row in rows:
            item = dict(row)
            dist = haversine_distance(lat, lon, item["latitude"], item["longitude"])
            if dist <= radius_km:
                item["distance"] = round(dist, 2)
                results.append(item)
        return sorted(results, key=lambda x: x["distance"])
    except Exception as e:
        print(f"SQLite fetch failed: {e}")
        return []

def save_pharmacies(pharmacies_list: list):
    if not pharmacies_list:
        return
        
    if USE_SUPABASE:
        try:
            payload = []
            for item in pharmacies_list:
                payload.append({
                    "id": str(item["id"]),
                    "name": item["name"],
                    "latitude": item["latitude"],
                    "longitude": item["longitude"],
                    "address": item.get("address") or "",
                    "phone": item.get("phone") or "",
                    "source": item.get("source") or "Unknown"
                })
            supabase_client.table("pharmacies").upsert(payload).execute()
            return
        except Exception as e:
            print(f"Failed to upsert to Supabase: {e}. Falling back to SQLite.")
            
    # SQLite
    try:
        conn = get_sqlite_connection()
        cursor = conn.cursor()
        for item in pharmacies_list:
            cursor.execute("""
                INSERT INTO pharmacies (id, name, latitude, longitude, address, phone, source) 
                VALUES (?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(id) DO UPDATE SET 
                    name=excluded.name, 
                    latitude=excluded.latitude, 
                    longitude=excluded.longitude, 
                    address=excluded.address, 
                    phone=excluded.phone, 
                    source=excluded.source
            """, (
                str(item["id"]),
                item["name"],
                item["latitude"],
                item["longitude"],
                item.get("address") or "",
                item.get("phone") or "",
                item.get("source") or "Unknown"
            ))
        conn.commit()
        conn.close()
    except Exception as e:
        print(f"Failed to save to SQLite: {e}")
